// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Backend.Context;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MyApi.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514050251_databaseCreate;")]
    partial class databaseCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Backend.Models.Medicine", b =>
                {
                    b.Property<int>("medicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEDICINE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("medicineId"));

                    b.Property<string>("medicineCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MEDICINE_CODE");

                    b.Property<string>("medicineName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MEDICINE_NAME");

                    b.Property<decimal>("price")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("stock")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOCK");

                    b.HasKey("medicineId");

                    b.ToTable("MEDICINES");
                });

            modelBuilder.Entity("MyApi.Backend.Models.Patient", b =>
                {
                    b.Property<int>("patientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientId"));

                    b.Property<DateTime>("arrival_date")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ARRIVAL_DATE");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PATIENT_NAME");

                    b.Property<int>("patientCase")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CASE");

                    b.Property<int>("status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HEALTHSTATUS");

                    b.HasKey("patientId");

                    b.ToTable("PATIENTS");
                });

            modelBuilder.Entity("MyApi.Backend.Models.PatientRoom", b =>
                {
                    b.Property<int>("patient_room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENT_ROOM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patient_room_id"));

                    b.Property<int>("PATIENT_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ROOM_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("USER_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.HasKey("patient_room_id");

                    b.HasIndex("PATIENT_ID");

                    b.HasIndex("ROOM_ID");

                    b.HasIndex("USER_ID");

                    b.ToTable("PATIENT_ROOM");
                });

            modelBuilder.Entity("MyApi.Backend.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROOM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("DAILY_RATE");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ROOM_NUMBER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROOM_TYPE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("RoomId");

                    b.ToTable("ROOMS");
                });

            modelBuilder.Entity("MyApi.Backend.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TRANSACTION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("MEDICINE_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PATIENT_ROOM_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TOTAL_COST");

                    b.Property<int>("isPaid")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ISPAID");

                    b.Property<int>("quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Quantity");

                    b.HasKey("TransactionId");

                    b.HasIndex("MEDICINE_ID");

                    b.HasIndex("PATIENT_ROOM_ID");

                    b.ToTable("TRANSACTIONS");
                });

            modelBuilder.Entity("MyApi.Backend.Models.Treatment", b =>
                {
                    b.Property<int>("treatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TREATMENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("treatmentId"));

                    b.Property<int>("PATIENT_ROOM_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("isPaid")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ISPAID");

                    b.Property<decimal>("totalCost")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TOTAL_COST");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPE");

                    b.HasKey("treatmentId");

                    b.HasIndex("PATIENT_ROOM_ID");

                    b.ToTable("TREATMENTS");
                });

            modelBuilder.Entity("MyApi.Backend.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USER_EMAIL");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USER_PASSWORD");

                    b.Property<int>("userRole")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ROLE");

                    b.HasKey("userId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("MyApi.Backend.Models.PatientRoom", b =>
                {
                    b.HasOne("MyApi.Backend.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("PATIENT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Backend.Models.Room", "room")
                        .WithMany()
                        .HasForeignKey("ROOM_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Backend.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");

                    b.Navigation("room");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MyApi.Backend.Models.Transaction", b =>
                {
                    b.HasOne("MyApi.Backend.Models.Medicine", "medicine")
                        .WithMany()
                        .HasForeignKey("MEDICINE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Backend.Models.PatientRoom", "patient_room")
                        .WithMany()
                        .HasForeignKey("PATIENT_ROOM_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicine");

                    b.Navigation("patient_room");
                });

            modelBuilder.Entity("MyApi.Backend.Models.Treatment", b =>
                {
                    b.HasOne("MyApi.Backend.Models.PatientRoom", "patient_room")
                        .WithMany()
                        .HasForeignKey("PATIENT_ROOM_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient_room");
                });
#pragma warning restore 612, 618
        }
    }
}
